apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: first-chart
    repoURL: "https://gebalamariusz.github.io/ArgoCD/helm-charts"
    targetRevision: 0.1.3
    helm:
      releaseName: helm-deployment
  syncPolicy:
    syncOptions:
      - CreateNamespace=true