apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: nginx
    repoURL: "https://github.com/gebalamariusz/ArgoCD/helm"
    targetRevision: HEAD
    helm:
      releaseName: helm-deployment
  syncPolicy:
    syncOptions:
      - CreateNamespace=true