apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-{{ .Values.name }}
  labels:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
spec:
  containers:
  - name: {{ .Values.name }}
    image: "{{ .Values.image.name }}:{{ .Values.image.version }}"