{{- if eq .Values.environment "prod" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: {{ .Values.loadBalancerType }}
    {{- if eq .Values.loadBalancerInternal }}
    service.beta.kubernetes.io/aws-load-balancer-internal: {{ .Values.loadBalancerInternal }}
    {{ end }}
spec:
  selector:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
  type: {{ .Values.serviceType }}
  ports:
    - protocol: {{ .Values.serviceProtocol }}
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.applicationPort }}
{{ end }}