{{- if eq .Values.labels.environment "prod" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "first-chart.fullname" . }}-svc
  annotations:
    {{- if .Values.loadBalancerExternal }}
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    {{- end }}
spec:
  selector: {{ include "first-chart.selectorLabels" . | indent 4 }}
  type: {{ .Values.serviceType }}
  ports:
    - protocol: {{ .Values.serviceProtocol }}
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.applicationPort }}
{{ end }}