global:
  edition: ce
  hosts:
    domain: gitlab.haitmg.pl
  registry:
    bucket: mgebala-eks-s3-bucket
    enabled: false

gitlab-runner:
  install: false

certmanager-issuer:
  email: gebalamariusz@gmail.com

upgradeCheck:
  enabled: false