global:
  edition: ce
  hosts:
    domain: haitmg.pl
  registry:
    enabled: true

s3:
  bucket: mgebala-eks-s3-bucket-virginia
  accesskey: AWS_ACCESS_KEY
  secretkey: AWS_SECRET_KEY
  region: eu-central-1

nginx-ingress:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

gitlab-runner:
  install: true

certmanager-issuer:
  email: gebalamariusz@gmail.com

upgradeCheck:
  enabled: false