global:
  edition: ce
  hosts:
    domain: haitmg.pl
  registry:
    enabled: true

nginx-ingress:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
       

gitlab-runner:
  install: true

certmanager-issuer:
  email: gebalamariusz@gmail.com

upgradeCheck:
  enabled: false