global:
  edition: ce
  hosts:
    domain: gitlab.haitmg.pl
  registry:
    region: eu-central-1
    bucket: mgebala-eks-s3-bucket
    enabled: true

gitlab-runner:
  install: false

certmanager-issuer:
  email: gebalamariusz@gmail.com

upgradeCheck:
  enabled: false