global:
  edition: ce
  hosts:
    domain: haitmg.pl
  registry:
    bucket: mgebala-eks-s3-bucket
    storage:
      s3:
        region: eu-central-1
    enabled: true

nginx-ingress:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

gitlab-runner:
  install: false

certmanager-issuer:
  email: gebalamariusz@gmail.com

upgradeCheck:
  enabled: false